### CREATE USER

POST http://localhost:3000/user/create
Content-Type: application/json

{
    "username": "darkmaper",
    "name": "DarkMaper",
    "email": "darkmaper@testing.com",
    "password": "MapehElMejoh"
}

### LOGIN USER
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "username": "darkmaper",
    "password": "MapehElMejoh"
}

### GET ALL USERS
GET http://localhost:3000/user/darkm

### Create Tweet
POST http://localhost:3000/tweets
Content-Type: application/json

{
    "autor": "syl_torres",
    "cuerpo": "Wiiiiiiiiiiiiiiiiiiiiiiiiiii"
}


### Get all tweets
GET http://localhost:3000/tweets

### Delete Tweet
DELETE http://localhost:3000/tweets/6053c859c7912f373046f123